spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# http://localhost:8080/h2-console로 들어가면 h2를 웹 브라우저로 확인할 수 있습니다.